# Generated by Django 4.0.2 on 2022-02-11 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keysrelatoriofiscal',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de expiração'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keysrelatoriofiscal',
            name='key',
            field=models.CharField(max_length=6, verbose_name='Chave de uso'),
        ),
    ]
